alter table public.generations
  add column if not exists quality_score integer,
  add column if not exists quality_reasons jsonb not null default '[]'::jsonb,
  add column if not exists strategy jsonb not null default '{}'::jsonb,
  add column if not exists alternatives jsonb not null default '[]'::jsonb;

create table if not exists public.trend_signals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  source text not null,
  external_id text not null,
  title text not null,
  description text not null,
  url text,
  tags jsonb not null default '[]'::jsonb,
  platform_hints jsonb not null default '[]'::jsonb,
  language text not null default 'en',
  region text not null default 'global',
  velocity_score numeric not null default 50,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, source, external_id)
);

create table if not exists public.trend_relevance_matches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  brand_profile_id bigint not null references public.brand_profiles(id) on delete cascade,
  signal_id bigint not null references public.trend_signals(id) on delete cascade,
  platform text not null,
  relevance_score integer not null,
  reasons jsonb not null default '[]'::jsonb,
  status text not null default 'candidate',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, brand_profile_id, signal_id, platform)
);

create table if not exists public.autopilot_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  brand_profile_id bigint not null references public.brand_profiles(id) on delete cascade,
  enabled boolean not null default true,
  platforms jsonb not null default '[]'::jsonb,
  min_relevance_score integer not null default 70,
  max_drafts_per_run integer not null default 2,
  post_type text not null default 'trend_based',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, brand_profile_id)
);

create table if not exists public.autopilot_runs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  brand_profile_id bigint not null references public.brand_profiles(id) on delete cascade,
  platform text not null,
  status text not null,
  max_drafts integer not null,
  created_drafts_count integer not null default 0,
  errors jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists idx_trend_signals_user_id on public.trend_signals(user_id);
create index if not exists idx_trend_matches_user_brand on public.trend_relevance_matches(user_id, brand_profile_id, platform);
create index if not exists idx_autopilot_runs_user_id on public.autopilot_runs(user_id, created_at desc);

drop trigger if exists trg_trend_signals_updated_at on public.trend_signals;
create trigger trg_trend_signals_updated_at
before update on public.trend_signals
for each row execute function public.handle_updated_at();

drop trigger if exists trg_trend_matches_updated_at on public.trend_relevance_matches;
create trigger trg_trend_matches_updated_at
before update on public.trend_relevance_matches
for each row execute function public.handle_updated_at();

drop trigger if exists trg_autopilot_settings_updated_at on public.autopilot_settings;
create trigger trg_autopilot_settings_updated_at
before update on public.autopilot_settings
for each row execute function public.handle_updated_at();

alter table public.trend_signals enable row level security;
alter table public.trend_relevance_matches enable row level security;
alter table public.autopilot_settings enable row level security;
alter table public.autopilot_runs enable row level security;

create policy "Users manage own trend signals"
on public.trend_signals
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users manage own trend matches"
on public.trend_relevance_matches
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users manage own autopilot settings"
on public.autopilot_settings
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users manage own autopilot runs"
on public.autopilot_runs
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
