create table if not exists public.trend_clusters (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  cluster_key text not null,
  canonical_title text not null,
  tags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, cluster_key)
);

create table if not exists public.trends (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  cluster_id bigint not null references public.trend_clusters(id) on delete cascade,
  title text not null,
  summary text not null,
  source_count integer not null default 1,
  momentum_score numeric not null default 0,
  confidence_score numeric not null default 0,
  latest_signal_at timestamptz,
  platform_hints jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trend_source_signals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  trend_id bigint references public.trends(id) on delete set null,
  source text not null,
  external_id text not null,
  title text not null,
  description text not null,
  url text,
  tags jsonb not null default '[]'::jsonb,
  platform_hints jsonb not null default '[]'::jsonb,
  language text not null default 'en',
  region text not null default 'global',
  velocity_score numeric not null default 50,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, source, external_id)
);

create table if not exists public.trend_embeddings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  trend_id bigint not null references public.trends(id) on delete cascade,
  embedding_model text not null,
  embedding jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, trend_id, embedding_model)
);

create table if not exists public.trend_momentum_windows (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  trend_id bigint not null references public.trends(id) on delete cascade,
  window_hours integer not null,
  signal_count integer not null default 0,
  avg_velocity numeric not null default 0,
  momentum_delta numeric not null default 0,
  computed_at timestamptz not null default now(),
  unique (user_id, trend_id, window_hours)
);

create table if not exists public.trend_ingestion_runs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  brand_profile_id bigint references public.brand_profiles(id) on delete set null,
  platform text,
  status text not null,
  discovered_count integer not null default 0,
  ingested_count integer not null default 0,
  evaluated_count integer not null default 0,
  error text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists idx_trend_clusters_user_key on public.trend_clusters(user_id, cluster_key);
create index if not exists idx_trends_user_updated on public.trends(user_id, updated_at desc);
create index if not exists idx_trend_source_signals_user_trend on public.trend_source_signals(user_id, trend_id);
create index if not exists idx_trend_momentum_windows_user_trend on public.trend_momentum_windows(user_id, trend_id, window_hours);
create index if not exists idx_trend_ingestion_runs_started on public.trend_ingestion_runs(started_at desc);

drop trigger if exists trg_trend_clusters_updated_at on public.trend_clusters;
create trigger trg_trend_clusters_updated_at
before update on public.trend_clusters
for each row execute function public.handle_updated_at();

drop trigger if exists trg_trends_updated_at on public.trends;
create trigger trg_trends_updated_at
before update on public.trends
for each row execute function public.handle_updated_at();

drop trigger if exists trg_trend_embeddings_updated_at on public.trend_embeddings;
create trigger trg_trend_embeddings_updated_at
before update on public.trend_embeddings
for each row execute function public.handle_updated_at();

alter table public.trend_clusters enable row level security;
alter table public.trends enable row level security;
alter table public.trend_source_signals enable row level security;
alter table public.trend_embeddings enable row level security;
alter table public.trend_momentum_windows enable row level security;
alter table public.trend_ingestion_runs enable row level security;

create policy "Users manage own trend clusters"
on public.trend_clusters
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users manage own canonical trends"
on public.trends
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users manage own trend source signals"
on public.trend_source_signals
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users manage own trend embeddings"
on public.trend_embeddings
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users manage own trend momentum windows"
on public.trend_momentum_windows
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users view own trend ingestion runs"
on public.trend_ingestion_runs
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
