create table if not exists public.trend_briefs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  brand_profile_id bigint not null references public.brand_profiles(id) on delete cascade,
  platform text not null,
  trend_title text not null,
  trend_description text not null,
  objective text not null,
  summary text not null,
  adaptation_angle text not null,
  do_list jsonb not null default '[]'::jsonb,
  dont_list jsonb not null default '[]'::jsonb,
  risk_notes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.generations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  brand_profile_id bigint not null references public.brand_profiles(id) on delete cascade,
  trend_brief_id bigint references public.trend_briefs(id) on delete set null,
  platform text not null,
  post_type text not null,
  topic text,
  tone text,
  caption text not null,
  hashtags jsonb not null default '[]'::jsonb,
  cta text,
  image_url text,
  used_headline text,
  image_direction text,
  safety_issues jsonb not null default '[]'::jsonb,
  safety_score integer not null default 100,
  created_at timestamptz not null default now()
);

create table if not exists public.draft_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  brand_profile_id bigint not null references public.brand_profiles(id) on delete cascade,
  platform text not null,
  caption text not null,
  hashtags jsonb not null default '[]'::jsonb,
  cta text,
  image_url text,
  status text not null default 'draft',
  scheduled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_trend_briefs_user_id on public.trend_briefs(user_id);
create index if not exists idx_generations_user_id on public.generations(user_id);
create index if not exists idx_draft_posts_user_id on public.draft_posts(user_id);
create index if not exists idx_usage_events_user_id_created_at on public.usage_events(user_id, created_at desc);

create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_draft_posts_updated_at on public.draft_posts;
create trigger trg_draft_posts_updated_at
before update on public.draft_posts
for each row
execute function public.handle_updated_at();

alter table public.trend_briefs enable row level security;
alter table public.generations enable row level security;
alter table public.draft_posts enable row level security;
alter table public.usage_events enable row level security;

create policy "Users manage own trend briefs"
on public.trend_briefs
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users manage own generations"
on public.generations
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users manage own draft posts"
on public.draft_posts
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users view own usage events"
on public.usage_events
for select
to authenticated
using (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('generated-posts', 'generated-posts', true)
on conflict (id) do nothing;

create policy "Generated posts public read"
on storage.objects
for select
to public
using (bucket_id = 'generated-posts');
